### ISSUE TITLE
v0.3: Support frozen-string-literal coexistence

### ISSUE THREAD

**Issue by miry** [wouterken/crystalruby#19]
The current version of master returns with next error when use `RUBYOPT="--enable=frozen-string-literal"`.

```
$ RUBYOPT="--enable=frozen-string-literal" bundle exec ruby examples/adder/adder.rb
/Users/miry/src/wouterken/crystalruby/lib/crystalruby/source_reader.rb:48:in `node_to_s': undefined method `accept' for nil (NoMethodError)

      SyntaxTree::Formatter.format("", node.accept(@visitor))
                                           ^^^^^^^
	from /Users/miry/src/wouterken/crystalruby/lib/crystalruby/source_reader.rb:73:in `extract_args_and_source_from_method'
	from /Users/miry/src/wouterken/crystalruby/lib/crystalruby/adapter.rb:178:in `define_crystalized_method'
	from /Users/miry/src/wouterken/crystalruby/lib/crystalruby/adapter.rb:108:in `method_added'
	from examples/adder/adder.rb:5:in `<module:Adder>'
	from examples/adder/adder.rb:3:in `<main>'
```

Debugging:

`SyntaxTree.search(method_source, :Params).first` returns `nil`

Note: It worked for [0.2.3](https://github.com/wouterken/crystalruby/releases/tag/0.2.3)

**Comment by miry** [comment]
I run some tests in SyntaxTree https://github.com/miry/syntax_tree/actions/runs/12072657747/job/33667110520, it seems it does not work well with latest ruby version.

**Comment by wouterken** [comment]
Thanks @miry 
I've switched to prism for Ruby parsing in 0.3.1, and now it seems to run without issues when `RUBYOPT="--enable=frozen-string-literal"`

🙏
