### ISSUE TITLE
"Crystalize" should be spelled "crystallize" to be grammatically-correct

### ISSUE THREAD

**Issue by pmarreck** [wouterken/crystalruby#20]
I may just be big on grammatical-correctness as well as code-correctness but this irritated me immediately so I am filing an issue!

**Comment by wouterken** [comment]
Thank you for reporting! I've adopted `crystallize` as the primary spelling of the method in v0.3.1.

(I've left an alias for the old form available, for both backwards compatibility, and as apparently it is also accepted by several dictionaries as a less commonly used variant of the same word).
