### ISSUE TITLE
Unexpected String Encoding Behavior in 0.3.1  

### ISSUE THREAD

**Issue by miry** [wouterken/crystalruby#22]
I've noticed some unexpected behavior in version `0.3.1`. It seems that `ffi` returns a binary string, which causes all strings from Crystal to have the `Encoding: ASCII-8BIT` by default in Ruby.  

Here’s a minimal example to demonstrate the issue:  

```ruby
require "crystalruby"

module StringManipulation
  crystallize :string
  def output
    "foo різних мов світу"
  end
end

str = StringManipulation.output
p str
p str.encoding
p str.force_encoding("UTF-8")
```

**Output:**  

```
$ bundle exec ruby examples/string/encoding.rb 
"foo \xD1\x80\xD1\x96\xD0\xB7\xD0\xBD\xD0\xB8\xD1\x85 \xD0\xBC\xD0\xBE\xD0\xB2 \xD1\x81\xD0\xB2\xD1\x96\xD1\x82\xD1\x83"
#<Encoding:ASCII-8BIT>
"foo різних мов світу"
```

In Crystal, strings are UTF-8 encoded by default. 
I’m wondering if there’s a way to ensure that UTF-8 encoding is set by default when strings are passed through `ffi`.  

Any guidance or workaround would be appreciated.

**Comment by wouterken** [comment]
Thanks for reporting! I've forced a default encoding of UTF-8 for strings in 0.3.2, which I think is a sound default given it matches that of Crystal.
