### ISSUE TITLE
Write Idiomatic Crystal and Ruby for examples.

### ISSUE THREAD

**Issue by jzakiya** [wouterken/crystalruby#23]
In the `primecount` benchmark example for Crystal and Ruby:

This snippet
```
(2..Math.sqrt(i).to_i).each do |j|
```
For Crystal would be this.
```
(2..Math.isqrt(i)).each do |j|
```
And for Ruby becomes:
```
(2..Integer.sqrt(i)).each do |j|
```
In each case, you don't need to do the `.to_i` conversion.

**Comment by wouterken** [comment]
Great suggestion, I've made the suggested change to the README now.
