### ISSUE TITLE
Interaction with rbs

### ISSUE THREAD

**Issue by Fryguy** [wouterken/crystalruby#6]
This is a similar question to #4 , but if a project uses [rbs](https://github.com/ruby/rbs) type definitions, could those eventually somehow be leveraged by the `crystalize` command?

**Comment by wouterken** [comment]
Hey @Fryguy 

It's definitely an interesting idea! 
I should note I want the library to easily slot into existing codebases, the vast majority of which I believe currently still ship without `rbs`, so I'd be inclined not to make it a firm dependency, but it's something that could potentially be leveraged if available, to simplify adoption. Crystal does a beautiful job of type inference to minimize the need for explicit type restrictions, and where possible it would be nice to leverage any existing, available type information, to achieve a similar design goal in this lib. 

One of my more immediate priorities will be exposing a more efficient means of passing complex types between Ruby and Crystal. This is already possible using FFI directly, but I want to settle on an ergonomic interface for exposing this via `crystalruby`.

Currently the library partially supports this using JSON serialization, which is easy to support, but far from the most performant option.
https://github.com/wouterken/crystalruby?tab=readme-ov-file#composite-types-using-json-serialization
