### ISSUE TITLE
A benchmark with JIT would be interesting

### ISSUE THREAD

**Issue by MadBomber** [wouterken/crystalruby#7]
I like the idea of a compiled Ruby.  Crystal comes close.  I even created a gem that is available as either Ruby or Crystal (`justprep`)

You gem is very interesting.  If you get a chance, generate a benchmark that shows how effect converting a method to Crystal is over waiting for the JIT compiler to decided its time to compile the method.

I've wondered for a while if the JIT could be "fooled" into just compiling the entire ruby application from the very beginning.

**Comment by wouterken** [comment]
Hey @MadBomber 

Here's a very unofficial benchmark quickly thrown together on my machine comparing a computationally expensive task in Crystal, with Ruby (no JIT) and Ruby (YJIT)

```ruby
require "benchmark"
require "crystalruby"

module PrimeCounter
  crystalize [s: :string] => :void
  def print(s)
    puts s
  end

  crystalize [n: :int32] => :int32
  def count_primes_upto_cr(n)
    (2..n).each.count do |i|
      is_prime = true
      (2..Math.sqrt(i).to_i).each do |j|
        if i % j == 0
          is_prime = false
          break
        end
      end
      is_prime
    end
  end

  module_function

  def count_primes_upto_rb(n)
    (2..n).each.count do |i|
      is_prime = true
      (2..Math.sqrt(i).to_i).each do |j|
        if i % j == 0
          is_prime = false
          break
        end
      end
      is_prime
    end
  end
end

Benchmark.bmbm do |x|
  x.report("Ruby (#{RubyVM::YJIT.enabled? ? "YJIT": "No JIT"})") { PrimeCounter.count_primes_upto_rb(2000_000) }
  x.report("Crystal") { PrimeCounter.count_primes_upto_cr(2000_000) }
end

```
It uses bmbm to hopefully give the JIT a chance to kick in.
Results after warmup:

```bash
                  user     system      total        real
Ruby (YJIT)   4.273526   0.013098   4.286624 (  4.288813)
Crystal       0.943466   0.007280   0.950746 (  0.954570)

                    user     system      total        real
Ruby (No JIT)   7.730069   0.045005   7.775074 (  7.784881)
Crystal         0.951092   0.010431   0.961523 (  0.962591)
```

On:
* Apple M1 Pro - 16GB 
* ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin22]

The YJIT Ruby version is impressively almost twice as fast as the no-JIT version, but the Crystal version is faster still, at 4x faster than JIT, and 8x faster then no-JIT.

**Comment by MadBomber** [comment]
Thank you!  I had a feeling that would be the case.  Too bad the majority of Ruby these days is all web-app based.  In the past I did lots of computationally complex simulations in Ruby.  I'm thinking that maybe some of the old AI code dealing with classifications, fann and nlp might be updated using `crystalruby`
